# This GitHub Actions workflow builds the code on pushes and pull requests.
# It checks out the code, sets up Node.js, installs dependencies, runs building,
# and prints a message if building fails.

name: Build|Transpile

on:
  push:
    branches: [main] # Run the workflow on pushes to the main branch
  pull_request:
    branches: [main] # Also run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v4 # Checkout the repository code
      - uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: 20

      # - run: npm install # Install dependencies

      - name: Run Build
        uses: icrawl/action-tsc@v1 # Execute the build command

      - name: Check for build errors
        if: failure() # Only run if the linting step failed
        run: echo "Build failed, check the errors above!"

      - name: Print Success Message
        if: success() # Only run if all previous steps were successful
        run: echo "Build completed successfully!"
