---
name: Build and Deploy to Cloud Run
on:
  push:
    branches: ["main"]
env:
  PROJECT_ID: webaas # TODO: update Google Cloud project id
  GAR_LOCATION: europe-west3 # TODO: update Artifact Registry location
  IMAGE_NAME: schoolwebapi
  SERVICE: school-web # TODO: update Cloud Run service name
  REGION: europe-west3 # TODO: update Cloud Run service region
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make envfile
        run: |
          echo "PORT=${{ env.PORT }}" >> .env
          echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v1

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker "${{env.GAR_LOCATION}}-docker.pkg.dev" --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ github.sha }}
        run: |-
          docker tag $IMAGE_NAME:latest "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.SERVICE}}/${{env.IMAGE_NAME}}:latest"
          docker tag "${{env.IMAGE_NAME}}:latest" "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.SERVICE}}/${{env.IMAGE_NAME}}:$GIT_TAG"
          docker push "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.SERVICE}}/${{env.IMAGE_NAME}}:latest"
          docker push "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.SERVICE}}/${{env.IMAGE_NAME}}:$GIT_TAG"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{env.IMAGE_NAME}}:latest

        # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
